# Re-export Prisma-generated ORM models so existing import paths keep working
from app.generated.models import (
    Activity,
    Agent,
    AuditLog,
    Company,
    Contact,
    Deal,
    Invoice,
    Lead,
    ProductCategory,
    PurchaseOrder,
    Quote,
    Sequence,
    SequenceEnrollment,
    Shipment,
    Supplier,
    User,
)

# Re-export shared enums so existing import paths keep working
from app.enums import (
    ActivityType,
    AgentRole,
    AgentStatus,
    DealStage,
    InvoiceStatus,
    LeadSource,
    LeadStage,
    ProcurementStatus,
    QuoteStatus,
    ShipmentStatus,
    SupplierStatus,
)

__all__ = [
    # ORM models
    "Activity",
    "Agent",
    "AuditLog",
    "Company",
    "Contact",
    "Deal",
    "Invoice",
    "Lead",
    "ProductCategory",
    "PurchaseOrder",
    "Quote",
    "Sequence",
    "SequenceEnrollment",
    "Shipment",
    "Supplier",
    "User",
    # Enums
    "ActivityType",
    "AgentRole",
    "AgentStatus",
    "DealStage",
    "InvoiceStatus",
    "LeadSource",
    "LeadStage",
    "ProcurementStatus",
    "QuoteStatus",
    "ShipmentStatus",
    "SupplierStatus",
]