apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../base

commonLabels:
  environment: staging

replicas:
  - name: agentic-crm-backend
    count: 1
  - name: agentic-crm-frontend
    count: 1
  - name: agentic-crm-celery
    count: 1

images:
  - name: agentic-crm-backend
    newTag: staging
  - name: agentic-crm-frontend
    newTag: staging