"""
Procurement Agent
Automates procurement request processing, supplier quoting, and order management.
"""
import json
import logging
from datetime import datetime, timedelta

from app.agents.context import AgentContext, get_current_correlation_id, get_current_run_id
from app.models import AgentRole
from app.prisma import prisma
from app.services.procurement_service import get_procurement_service
from app.services.supplier_matching_service import get_supplier_matching_service

logger = logging.getLogger(__name__)


async def process_procurement_requests(min_priority: str = "medium", correlation_id: str | None = None):
    """
    Find pending procurement requests and match them to suppliers.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.OUTREACH)

    logger.info(
        f"Processing procurement requests: min_priority={min_priority}",
        extra={"run_id": run_id, "correlation_id": corr_id}
    )

    try:
        procurement_service = await get_procurement_service()
        supplier_matching = await get_supplier_matching_service()

        requests = await prisma.procurementrequest.find_many(
            where={"status": "SUBMITTED"},
            order={"createdAt": "desc"},
            take=20,
        )

        processed = []
        for req in requests:
            extra_data = json.loads(req.extra_data) if req.extra_data else {}
            top_suppliers = await supplier_matching.get_top_suppliers_for_rfq(
                rfq_industry=extra_data.get("industry", "General") if extra_data else "General",
                rfq_countries=["Turkey", "Germany", "Italy", "Spain"],
                top_n=5,
            )

            for supplier_match in top_suppliers:
                supplier = await prisma.supplier.find_unique(
                    where={"id": supplier_match.supplier_id}
                )
                if not supplier:
                    continue

                price = req.target_price or (1000 * (1 + supplier_match.match_score))

                await procurement_service.create_quote(
                    procurement_request_id=req.id,
                    supplier_id=supplier.id,
                    price=price,
                    lead_time_days=30,
                    notes=f"Quote generated by AI procurement agent based on supplier matching (score: {supplier_match.match_score:.2f})",
                )

            if top_suppliers:
                processed.append(req.id)

        await prisma.auditlog.create(
            data={
                "action": "procurement_processed",
                "entityType": "procurement_request",
                "entityId": 0,
                "details": json.dumps({
                    "count": len(processed),
                    "request_ids": processed,
                    "run_id": run_id,
                    "correlation_id": corr_id,
                }),
            }
        )

        logger.info(f"Procurement requests processed: {len(processed)}", extra={"run_id": run_id})
        return {
            "status": "completed",
            "processed_count": len(processed),
            "request_ids": processed,
            "run_id": run_id,
        }
    except Exception as e:
        logger.error(f"Error processing procurement requests: {e}", extra={"run_id": run_id})
        return {"status": "error", "message": str(e)}


async def check_shipment_status(correlation_id: str | None = None):
    """
    Check status of shipments and update purchase order statuses.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.REPORTING)

    logger.info(
        "Checking shipment statuses",
        extra={"run_id": run_id, "correlation_id": corr_id}
    )

    try:
        cutoff = datetime.utcnow() + timedelta(days=3)
        shipments = await prisma.shipment.find_many(
            where={
                "status": "IN_TRANSIT",
                "estimatedDeliveryDate": {"lte": cutoff.isoformat()},
            }
        )

        alerts = []
        for shipment in shipments:
            if shipment.estimatedDeliveryDate:
                est_date = datetime.fromisoformat(shipment.estimatedDeliveryDate)
                if est_date < datetime.utcnow():
                    alerts.append({
                        "shipment_id": shipment.id,
                        "tracking_number": shipment.trackingNumber,
                        "status": "overdue",
                        "estimated_delivery": shipment.estimatedDeliveryDate,
                    })

        if alerts:
            await prisma.auditlog.create(
                data={
                    "action": "shipment_alerts",
                    "entityType": "shipment",
                    "entityId": 0,
                    "details": json.dumps({
                        "count": len(alerts),
                        "shipments": alerts,
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    }),
                }
            )

        logger.info(f"Shipment check completed: {len(alerts)} alerts", extra={"run_id": run_id})
        return {
            "status": "completed",
            "alert_count": len(alerts),
            "alerts": alerts,
            "run_id": run_id,
        }
    except Exception as e:
        logger.error(f"Error checking shipment status: {e}", extra={"run_id": run_id})
        return {"status": "error", "message": str(e)}


async def process_supplier_payments(days_overdue: int = 7, correlation_id: str | None = None):
    """
    Find overdue invoices and flag them for payment processing.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.REPORTING)

    logger.info(
        f"Processing supplier payments: days_overdue={days_overdue}",
        extra={"run_id": run_id, "correlation_id": corr_id}
    )

    try:
        cutoff = datetime.utcnow() - timedelta(days=days_overdue)
        invoices = await prisma.invoice.find_many(
            where={
                "status": "SENT",
                "dueDate": {"lt": cutoff.isoformat()},
            }
        )

        overdue_ids = []
        for invoice in invoices:
            await prisma.invoice.update(
                where={"id": invoice.id},
                data={"status": "OVERDUE"}
            )
            await prisma.activity.create(
                data={
                    "purchaseOrderId": invoice.purchaseOrderId,
                    "type": "AGENT_ACTION",
                    "content": f"Invoice {invoice.invoiceNumber} marked overdue by procurement agent",
                    "activityMeta": json.dumps({
                        "action": "invoice_overdue",
                        "invoice_id": invoice.id,
                        "days_overdue": days_overdue,
                    }),
                }
            )
            overdue_ids.append(invoice.id)

        if overdue_ids:
            await prisma.auditlog.create(
                data={
                    "action": "overdue_invoices_processed",
                    "entityType": "invoice",
                    "entityId": 0,
                    "details": json.dumps({
                        "count": len(overdue_ids),
                        "invoice_ids": overdue_ids,
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    }),
                }
            )

        logger.info(f"Payment processing completed: {len(overdue_ids)} overdue", extra={"run_id": run_id})
        return {
            "status": "completed",
            "overdue_count": len(overdue_ids),
            "invoice_ids": overdue_ids,
            "run_id": run_id,
        }
    except Exception as e:
        logger.error(f"Error processing supplier payments: {e}", extra={"run_id": run_id})
        return {"status": "error", "message": str(e)}


async def auto_close_completed_orders(correlation_id: str | None = None):
    """
    Automatically close purchase orders that have been fully delivered and paid.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.OUTREACH)

    logger.info(
        "Auto-closing completed orders",
        extra={"run_id": run_id, "correlation_id": corr_id}
    )

    try:
        orders = await prisma.purchaseorder.find_many(
            where={"status": "SHIPPED"}
        )

        closed = []
        for order in orders:
            shipments = await prisma.shipment.find_many(
                where={"purchaseOrderId": order.id}
            )
            all_delivered = all(s.status == "DELIVERED" for s in shipments)

            invoices = await prisma.invoice.find_many(
                where={"purchaseOrderId": order.id}
            )
            all_paid = all(inv.status == "PAID" for inv in invoices)

            if all_delivered and all_paid:
                await prisma.purchaseorder.update(
                    where={"id": order.id},
                    data={"status": "DELIVERED"}
                )
                closed.append(order.id)

        if closed:
            await prisma.auditlog.create(
                data={
                    "action": "orders_auto_closed",
                    "entityType": "purchase_order",
                    "entityId": 0,
                    "details": json.dumps({
                        "count": len(closed),
                        "order_ids": closed,
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    }),
                }
            )

        logger.info(f"Orders auto-closed: {len(closed)}", extra={"run_id": run_id})
        return {
            "status": "completed",
            "closed_count": len(closed),
            "order_ids": closed,
            "run_id": run_id,
        }
    except Exception as e:
        logger.error(f"Error auto-closing orders: {e}", extra={"run_id": run_id})
        return {"status": "error", "message": str(e)}
