"""
Procurement Agent
Automates procurement request processing, supplier quoting, and order management.
"""
import logging
from datetime import datetime, timedelta

from sqlalchemy import select

from app.agents._async import run_async
from app.agents.context import AgentContext, get_current_correlation_id, get_current_run_id
from app.celery_app import celery_app
from app.db.database import get_async_session_local
from app.models.models import (
    Activity,
    ActivityType,
    AgentRole,
    AuditLog,
    ProcurementRequest,
    ProcurementStatus,
    PurchaseOrder,
    PurchaseOrderStatus,
    Quote,
    QuoteStatus,
    Shipment,
    ShipmentStatus,
    Supplier,
    SupplierStatus,
)
from app.services.procurement_service import get_procurement_service
from app.services.supplier_matching_service import get_supplier_matching_service

logger = logging.getLogger(__name__)


@celery_app.task(
    name="agents.procurement.process_requests",
    bind=True,
    max_retries=3,
    default_retry_delay=120,
    autoretry_for=(Exception,),
    retry_backoff=True,
)
def process_procurement_requests(self, min_priority: str = "medium", correlation_id: str | None = None):
    """
    Find pending procurement requests and match them to suppliers.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.OUTREACH)

    logger.info(
        f"Processing procurement requests: min_priority={min_priority}",
        extra={"run_id": run_id, "correlation_id": corr_id, "task_name": self.name}
    )

    async def _process():
        SessionLocal = get_async_session_local()
        if SessionLocal is None:
            logger.error("Database not configured", extra={"run_id": run_id})
            return {"status": "error", "message": "Database not configured"}

        procurement_service = await get_procurement_service()
        supplier_matching = await get_supplier_matching_service()
        async with SessionLocal() as db:
            result = await db.execute(
                select(ProcurementRequest)
                .where(ProcurementRequest.status == ProcurementStatus.SUBMITTED)
                .order_by(ProcurementRequest.created_at.desc())
                .limit(20)
            )
            requests = result.scalars().all()

            processed = []
            for req in requests:
                top_suppliers = await supplier_matching.get_top_suppliers_for_rfq(
                    rfq_industry=req.extra_data.get("industry", "General") if req.extra_data else "General",
                    rfq_countries=["Turkey", "Germany", "Italy", "Spain"],
                    top_n=5,
                )

                for supplier_match in top_suppliers:
                    supplier_result = await db.execute(
                        select(Supplier).where(Supplier.id == supplier_match.supplier_id)
                    )
                    supplier = supplier_result.scalar_one_or_none()
                    if not supplier:
                        continue

                    price = req.target_price or (1000 * (1 + supplier_match.match_score))

                    await procurement_service.create_quote(
                        procurement_request_id=req.id,
                        supplier_id=supplier.id,
                        price=price,
                        lead_time_days=30,
                        notes=f"Quote generated by AI procurement agent based on supplier matching (score: {supplier_match.match_score:.2f})",
                    )

                if top_suppliers:
                    processed.append(req.id)

            audit = AuditLog(
                action="procurement_processed",
                entity_type="procurement_request",
                entity_id=0,
                details={
                    "count": len(processed),
                    "request_ids": processed,
                    "run_id": run_id,
                    "correlation_id": corr_id,
                },
            )
            db.add(audit)
            await db.commit()

            logger.info(f"Procurement requests processed: {len(processed)}", extra={"run_id": run_id})
            return {
                "status": "completed",
                "processed_count": len(processed),
                "request_ids": processed,
                "run_id": run_id,
            }

    return run_async(_process())


@celery_app.task(
    name="agents.procurement.check_shipment_status",
    bind=True,
    max_retries=3,
    default_retry_delay=60,
    autoretry_for=(Exception,),
    retry_backoff=True,
)
def check_shipment_status(self, correlation_id: str | None = None):
    """
    Check status of shipments and update purchase order statuses.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.REPORTING)

    logger.info(
        f"Checking shipment statuses",
        extra={"run_id": run_id, "correlation_id": corr_id, "task_name": self.name}
    )

    async def _check():
        SessionLocal = get_async_session_local()
        if SessionLocal is None:
            logger.error("Database not configured", extra={"run_id": run_id})
            return {"status": "error", "message": "Database not configured"}

        async with SessionLocal() as db:
            result = await db.execute(
                select(Shipment)
                .where(Shipment.status == ShipmentStatus.IN_TRANSIT)
                .where(Shipment.estimated_delivery_date <= datetime.utcnow() + timedelta(days=3))
            )
            shipments = result.scalars().all()

            alerts = []
            for shipment in shipments:
                if shipment.estimated_delivery_date and shipment.estimated_delivery_date < datetime.utcnow():
                    alerts.append({
                        "shipment_id": shipment.id,
                        "tracking_number": shipment.tracking_number,
                        "status": "overdue",
                        "estimated_delivery": shipment.estimated_delivery_date.isoformat() if shipment.estimated_delivery_date else None,
                    })

            if alerts:
                audit = AuditLog(
                    action="shipment_alerts",
                    entity_type="shipment",
                    entity_id=0,
                    details={
                        "count": len(alerts),
                        "shipments": alerts,
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    },
                )
                db.add(audit)
                await db.commit()

            logger.info(f"Shipment check completed: {len(alerts)} alerts", extra={"run_id": run_id})
            return {
                "status": "completed",
                "alert_count": len(alerts),
                "alerts": alerts,
                "run_id": run_id,
            }

    return run_async(_check())


@celery_app.task(
    name="agents.procurement.process_supplier_payments",
    bind=True,
    max_retries=3,
    default_retry_delay=120,
    autoretry_for=(Exception,),
    retry_backoff=True,
)
def process_supplier_payments(self, days_overdue: int = 7, correlation_id: str | None = None):
    """
    Find overdue invoices and flag them for payment processing.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.REPORTING)

    logger.info(
        f"Processing supplier payments: days_overdue={days_overdue}",
        extra={"run_id": run_id, "correlation_id": corr_id, "task_name": self.name}
    )

    async def _process():
        SessionLocal = get_async_session_local()
        if SessionLocal is None:
            logger.error("Database not configured", extra={"run_id": run_id})
            return {"status": "error", "message": "Database not configured"}

        from app.models.models import Invoice, InvoiceStatus

        async with SessionLocal() as db:
            cutoff = datetime.utcnow() - timedelta(days=days_overdue)
            result = await db.execute(
                select(Invoice)
                .where(Invoice.status == InvoiceStatus.SENT)
                .where(Invoice.due_date < cutoff)
            )
            overdue_invoices = result.scalars().all()

            for invoice in overdue_invoices:
                invoice.status = InvoiceStatus.OVERDUE

                activity = Activity(
                    purchase_order_id=invoice.purchase_order_id,
                    type=ActivityType.AGENT_ACTION,
                    content=f"Invoice {invoice.invoice_number} marked overdue by procurement agent",
                    activity_meta={
                        "action": "invoice_overdue",
                        "invoice_id": invoice.id,
                        "days_overdue": days_overdue,
                    },
                )
                db.add(activity)

            if overdue_invoices:
                audit = AuditLog(
                    action="overdue_invoices_processed",
                    entity_type="invoice",
                    entity_id=0,
                    details={
                        "count": len(overdue_invoices),
                        "invoice_ids": [inv.id for inv in overdue_invoices],
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    },
                )
                db.add(audit)
                await db.commit()

            logger.info(f"Payment processing completed: {len(overdue_invoices)} overdue", extra={"run_id": run_id})
            return {
                "status": "completed",
                "overdue_count": len(overdue_invoices),
                "invoice_ids": [inv.id for inv in overdue_invoices],
                "run_id": run_id,
            }

    return run_async(_process())


@celery_app.task(
    name="agents.procurement.auto_close_completed_orders",
    bind=True,
    max_retries=3,
    default_retry_delay=60,
    autoretry_for=(Exception,),
    retry_backoff=True,
)
def auto_close_completed_orders(self, correlation_id: str | None = None):
    """
    Automatically close purchase orders that have been fully delivered and paid.
    """
    run_id = get_current_run_id()
    corr_id = correlation_id or get_current_correlation_id()
    AgentContext(role=AgentRole.OUTREACH)

    logger.info(
        f"Auto-closing completed orders",
        extra={"run_id": run_id, "correlation_id": corr_id, "task_name": self.name}
    )

    async def _close():
        SessionLocal = get_async_session_local()
        if SessionLocal is None:
            logger.error("Database not configured", extra={"run_id": run_id})
            return {"status": "error", "message": "Database not configured"}

        from app.models.models import InvoiceStatus

        async with SessionLocal() as db:
            result = await db.execute(
                select(PurchaseOrder)
                .where(PurchaseOrder.status == PurchaseOrderStatus.SHIPPED)
            )
            orders = result.scalars().all()

            closed = []
            for order in orders:
                shipments_result = await db.execute(
                    select(Shipment).where(Shipment.purchase_order_id == order.id)
                )
                shipments = shipments_result.scalars().all()

                all_delivered = all(s.status == ShipmentStatus.DELIVERED for s in shipments)

                invoices_result = await db.execute(
                    select(Invoice).where(Invoice.purchase_order_id == order.id)
                )
                invoices = invoices_result.scalars().all()
                all_paid = all(inv.status == InvoiceStatus.PAID for inv in invoices)

                if all_delivered and all_paid:
                    order.status = PurchaseOrderStatus.DELIVERED
                    closed.append(order.id)

            if closed:
                audit = AuditLog(
                    action="orders_auto_closed",
                    entity_type="purchase_order",
                    entity_id=0,
                    details={
                        "count": len(closed),
                        "order_ids": closed,
                        "run_id": run_id,
                        "correlation_id": corr_id,
                    },
                )
                db.add(audit)
                await db.commit()

            logger.info(f"Orders auto-closed: {len(closed)}", extra={"run_id": run_id})
            return {
                "status": "completed",
                "closed_count": len(closed),
                "order_ids": closed,
                "run_id": run_id,
            }

    return run_async(_close())